In [54]:
import numpy as np
import pandas as pd

In [55]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

def group_standardize(series):
    scaler = StandardScaler()
    return scaler.fit_transform(series.values.reshape(-1, 1)).ravel()

In [56]:
data=pd.read_csv("Abilities.csv")

In [57]:
reldata=data[data["Element Name"].isin(['Written Comprehension',
'Problem Sensitivity',
'Deductive Reasoning',
'Inductive Reasoning',
'Information Ordering',
'Mathematical Reasoning',
'Memorization',
'Speed of Closure',
'Flexibility of Closure',
'Perceptual Speed',
'Visualization',
'Spatial Orientation',
'Selective Attention',
'Time Sharing'])]

In [58]:
df=pd.read_csv("battery26_df.csv")

In [59]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['z'] = (
    df.groupby('specific_subtest_id')['raw_score']
      .transform(lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).ravel())
)

In [60]:
subtest_ability_map = pd.DataFrame({
    "specific_subtest_id": [
        29, 51,        # Mathematical reasoning
        31,            # Inductive reasoning
        30,            # Written comprehension
        26, 32, 40,    # Problem sensitivity
        28, 33, 36, 37, 53,  # Memorization
        52, 39,        # Selective attention
        27, 55,        # Divided attention
        38, 45         # Perceptual speed
    ],
    "Ability": [
        "Mathematical Reasoning", "Mathematical Reasoning",
        "Inductive Reasoning",
        "Written Comprehension",
        "Problem Sensitivity", "Problem Sensitivity", "Problem Sensitivity",
        "Memorization", "Memorization", "Memorization", "Memorization", "Memorization",
        "Selective Attention", "Selective Attention",
        "Time Sharing", "Time Sharing",
        "Perceptual Speed", "Perceptual Speed"
    ]
})
 # "Deductive Reasoning",
 #        "Selective Attention",
 #        "Memorization",
 #        "Speed of Closure",
 #        "Time Sharing"

In [61]:
df_with_abilities = df.merge(
    subtest_ability_map,
    on="specific_subtest_id",
    how="left"
)

In [62]:
df_clean=df_with_abilities[['user_id','test_run_id','battery_id', 'specific_subtest_id', 'raw_score', 'time_of_day',
       'grand_index', 'z', 'Ability']]

In [63]:
df2=pd.read_csv("battery60_norms.csv")

In [64]:
df2_raw=pd.read_csv("battery60_df.csv")

In [65]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df2_raw['z'] = (
    df2_raw.groupby('specific_subtest_id')['raw_score']
      .transform(lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).ravel())
)


subtest_ability_map = pd.DataFrame({
    "specific_subtest_id": [
        51,  # Scale balance
        52,  # Posner cueing
        53,  # Complex memory span
        54,  # Object recognition
        55   # Dual search
    ],
    "Ability": [
        "Deductive Reasoning",
        "Selective Attention",
        "Memorization",
        "Speed of Closure",
        "Time Sharing"   # (Divided Attention / Flexibility of Closure)
    ]
})
df_with_abilities2 = df2_raw.merge(
    subtest_ability_map,
    on="specific_subtest_id",
    how="left"
)
df_clean2=df_with_abilities2[['user_id','test_run_id','battery_id', 'specific_subtest_id', 'raw_score', 'time_of_day',
       'grand_index', 'z', 'Ability']]

In [66]:
df_final=pd.concat([df_clean, df_clean2])

In [67]:
df_final.info

<bound method DataFrame.info of          user_id  test_run_id  battery_id  specific_subtest_id  raw_score  \
0          68983       251259          26                   36       10.0
1          68983       251259          26                   39       19.0
2          68983       251259          26                   40       28.0
3          68983       251259          26                   29       17.0
4          68983       251259          26                   28        6.0
...          ...          ...         ...                  ...        ...
46599  105442892       556419          60                   54       34.0
46600  105442892       556419          60                   52       99.0
46601  105442892       556419          60                   53        8.0
46602  105442892       556419          60                   55       39.0
46603  105442892       556419          60                   51        3.0

       time_of_day  grand_index         z                 Ability
0               13   106.315883  0.215083            Memorization
1               13   106.315883 -0.354130     Selective Attention
2               13   106.315883 -0.544439     Problem Sensitivity
3               13   106.315883  0.298649  Mathematical Reasoning
4               13   106.315883  0.229481            Memorization
...            ...          ...       ...                     ...
46599           20    91.400997  0.297396        Speed of Closure
46600           20    91.400997  0.170917     Selective Attention
46601           20    91.400997 -0.213934            Memorization
46602           20    91.400997 -0.408040            Time Sharing
46603           20    91.400997 -1.557862     Deductive Reasoning

[61415 rows x 9 columns]>

In [68]:
ability_means = (
    df_final
    .groupby('Ability')['z']
    .mean()
    .reset_index()
    .sort_values('z', ascending=False)
)

In [69]:
from scipy.stats import zscore

reldata_norm = (
    reldata
    .query("`Scale ID` in ['IM','LV']")
    .pivot_table(
        index=["O*NET-SOC Code", "Title", "Element Name"],
        columns="Scale ID",
        values="Data Value"
    )
    .rename(columns={"IM": "importance", "LV": "level"})
    .reset_index()
    .assign(
        combined = lambda df: df["importance"] * df["level"]
    )
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

reldata_norm["ability_score"] = (
    reldata_norm
    .groupby("Element Name")["combined"]
    .transform(lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).ravel())
)

In [70]:
abilities = df_final["Ability"].unique()

reldata_small = reldata_norm[
    reldata_norm["Element Name"].isin(abilities)
]

In [71]:
job_abilities = (
    reldata_small
    [["O*NET-SOC Code", "Title", "Element Name", "ability_score"]]
)

In [72]:
job_abilities.head(20)

Scale ID,O*NET-SOC Code,Title,Element Name,ability_score
0,11-1011.00,Chief Executives,Deductive Reasoning,1.700598
4,11-1011.00,Chief Executives,Mathematical Reasoning,1.240398
5,11-1011.00,Chief Executives,Memorization,1.513427
6,11-1011.00,Chief Executives,Perceptual Speed,0.435258
7,11-1011.00,Chief Executives,Problem Sensitivity,1.695923
8,11-1011.00,Chief Executives,Selective Attention,0.125927
10,11-1011.00,Chief Executives,Speed of Closure,1.382432
11,11-1011.00,Chief Executives,Time Sharing,0.845001
13,11-1011.00,Chief Executives,Written Comprehension,1.529377
14,11-1011.03,Chief Sustainability Officers,Deductive Reasoning,1.412101
18,11-1011.03,Chief Sustainability Officers,Mathematical Reasoning,0.290609
19,11-1011.03,Chief Sustainability Officers,Memorization,0.309428
20,11-1011.03,Chief Sustainability Officers,Perceptual Speed,-1.400228
21,11-1011.03,Chief Sustainability Officers,Problem Sensitivity,0.756294
22,11-1011.03,Chief Sustainability Officers,Selective Attention,0.125927
24,11-1011.03,Chief Sustainability Officers,Speed of Closure,-0.027604
25,11-1011.03,Chief Sustainability Officers,Time Sharing,-0.271521
27,11-1011.03,Chief Sustainability Officers,Written Comprehension,0.743190
28,11-1021.00,General and Operations Managers,Deductive Reasoning,0.793504
32,11-1021.00,General and Operations Managers,Mathematical Reasoning,0.468048

In [73]:
person_ability = (
    df_final
    .groupby(["user_id", "Ability"])["z"]
    .mean()
    .reset_index()
)

In [74]:
person_ability.head(20)

    user_id              Ability         z
0     11545  Deductive Reasoning  1.230279
1     11545         Memorization  0.611160
2     11545  Selective Attention  0.315301
3     11545     Speed of Closure  1.284451
4     11545         Time Sharing  0.690992
5     18954  Deductive Reasoning  1.230279
6     18954         Memorization  0.886191
7     18954  Selective Attention  0.170917
8     18954     Speed of Closure  1.037687
9     18954         Time Sharing  0.251380
10    19050  Deductive Reasoning -0.070853
11    19050         Memorization -0.488965
12    19050  Selective Attention  0.170917
13    19050     Speed of Closure -0.689658
14    19050         Time Sharing -0.188233
15    29377  Deductive Reasoning -0.628482
16    29377         Memorization -0.488965
17    29377  Selective Attention  0.026533
18    29377     Speed of Closure  0.050633
19    29377         Time Sharing -0.627846

In [75]:
ja_pivot=job_abilities.pivot_table(
    index='Title',
    columns='Element Name',
    values='ability_score'
)

In [76]:
pa_pivot=person_ability.pivot_table(index='user_id',
    columns='Ability',
    values='z')

In [77]:
ja_pivot=ja_pivot.dropna()

In [78]:
ja_pivot

Element Name,Deductive Reasoning,Mathematical Reasoning,Memorization,Perceptual Speed,Problem Sensitivity,Selective Attention,Speed of Closure,Time Sharing,Written Comprehension
Title,,,,,,,,,
Accountants and Auditors,1.018582,1.357991,-0.124991,0.109817,0.613903,-0.981324,0.901529,-0.749085,0.635983
Actors,-1.065427,-1.699426,4.736982,-1.838489,-0.905604,0.125927,-0.689027,0.641958,0.024271
Actuaries,1.687944,3.872671,0.163898,-0.033377,0.756294,1.117597,0.256172,-0.778912,1.163611
Acupuncturists,0.557847,-0.734560,-0.946074,-0.343631,0.508732,-0.093765,-0.810877,-0.670449,0.322770
Acute Care Nurses,1.043736,0.384683,1.342935,0.435258,2.020264,0.601929,1.551398,1.227660,1.082680
...,...,...,...,...,...,...,...,...,...
Wind Turbine Service Technicians,0.302553,-0.548824,0.987744,0.753929,0.356026,0.354408,0.571223,1.219851,-0.610038
"Woodworking Machine Setters, Operators, and Tenders, Except Sawing",-1.065427,-0.792452,-1.064471,0.591469,-1.005139,1.306410,0.260956,-0.456234,-1.086816
Word Processors and Typists,-1.065427,-0.620127,-1.192734,0.435258,-1.387966,-1.403135,-0.689027,-1.359191,0.023220
Writers and Authors,-0.583182,-1.532986,-0.712042,-1.951308,-0.797774,-1.390563,0.256172,-0.941607,0.850397
Zoologists and Wildlife Biologists,0.797148,0.471521,-0.566217,0.109817,0.374636,0.859763,-0.049311,1.227660,1.373821

In [79]:
pa_pivot_clean = pa_pivot.copy()

In [80]:
pa_pivot_clean['ability_count'] = pa_pivot.notna().sum(axis=1)

In [81]:
user_counts = (
    pa_pivot_clean
    .groupby('ability_count')
    .size()
)

In [82]:
pa_new=pa_pivot_clean[pa_pivot_clean["ability_count"]>=5]

In [83]:
job_abilities.to_csv("job_to_ability_raw.csv")

In [84]:
ja_pivot.to_csv("job_abilities_matrix.csv")

In [85]:
pa_new= pa_new.drop('ability_count', axis=1)

In [86]:
pa_new.to_csv("abilities_dist_matrix.csv")

In [87]:
ability_dist_matrix=pa_new

In [88]:
ability_job_matrix=ja_pivot

## work abilities

In [89]:
atwa=pd.read_csv("Abilities to Work Activities.csv")

In [90]:
wa=pd.read_csv("Work Activities.csv")

In [101]:
atwa_matrix = (
    atwa
    .assign(value=1)
    .pivot_table(
        index="Work Activities Element Name",
        columns="Abilities Element Name",
        values="value",
        fill_value=0
    )
)

In [103]:
ja_pivot.columns

Index(['Deductive Reasoning', 'Mathematical Reasoning', 'Memorization',
       'Perceptual Speed', 'Problem Sensitivity', 'Selective Attention',
       'Speed of Closure', 'Time Sharing', 'Written Comprehension'],
      dtype='object', name='Element Name')

In [104]:
atwa_matrix=atwa_matrix[['Deductive Reasoning', 'Mathematical Reasoning', 'Memorization',
       'Perceptual Speed', 'Problem Sensitivity', 'Selective Attention',
       'Speed of Closure', 'Time Sharing', 'Written Comprehension']]

In [105]:
atwa_matrix

Abilities Element Name,Deductive Reasoning,Mathematical Reasoning,Memorization,Perceptual Speed,Problem Sensitivity,Selective Attention,Speed of Closure,Time Sharing,Written Comprehension
Work Activities Element Name,,,,,,,,,
Analyzing Data or Information,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
Assisting and Caring for Others,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Coaching and Developing Others,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Communicating with People Outside the Organization,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
"Communicating with Supervisors, Peers, or Subordinates",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Controlling Machines and Processes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Coordinating the Work and Activities of Others,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Developing Objectives and Strategies,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Developing and Building Teams,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Documenting/Recording Information,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
"Drafting, Laying Out, and Specifying Technical Devices, Parts, and Equipment",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Establishing and Maintaining Interpersonal Relationships,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
"Estimating the Quantifiable Characteristics of Products, Events, or Information",1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Evaluating Information to Determine Compliance with Standards,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
Getting Information,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
"Guiding, Directing, and Motivating Subordinates",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
Handling and Moving Objects,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Identifying Objects, Actions, and Events",1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
"Inspecting Equipment, Structures, or Materials",1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
Interpreting the Meaning of Information for Others,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
"Judging the Qualities of Objects, Services, or People",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Making Decisions and Solving Problems,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
"Monitoring Processes, Materials, or Surroundings",1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0
Monitoring and Controlling Resources,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
"Operating Vehicles, Mechanized Devices, or Equipment",0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
"Organizing, Planning, and Prioritizing Work",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Performing Administrative Activities,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Performing General Physical Activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Performing for or Working Directly with the Public,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
Processing Information,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
Providing Consultation and Advice to Others,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
Repairing and Maintaining Electronic Equipment,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
Repairing and Maintaining Mechanical Equipment,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
Resolving Conflicts and Negotiating with Others,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
Scheduling Work and Activities,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Selling or Influencing Others,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
Staffing Organizational Units,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
Thinking Creatively,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Training and Teaching Others,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
Updating and Using Relevant Knowledge,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Working with Computers,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [106]:
atwa_matrix.shape

(41, 9)

In [93]:
wa_c = (
    wa
    .query("`Scale ID` in ['IM','LV']")
    .pivot_table(
        index=["O*NET-SOC Code","Title","Element Name"],
        columns="Scale ID",
        values="Data Value"
    )
    .rename(columns={"IM":"importance","LV":"level"})
    .reset_index()
)

In [94]:
wa_c["combined_score"] = (
    wa_c["importance"] * wa_c["level"]
)

In [95]:
wa_c["activity_score"] = (
    wa_c
    .groupby("Element Name")["combined_score"]
    .transform(group_standardize)
)

In [96]:
wa_final = (
    wa_c
    .pivot_table(
        index="Title",
        columns="Element Name",
        values="activity_score"
    )
    .fillna(0)
)

In [97]:
wa_final

Element Name,Analyzing Data or Information,Assisting and Caring for Others,Coaching and Developing Others,Communicating with People Outside the Organization,"Communicating with Supervisors, Peers, or Subordinates",Controlling Machines and Processes,Coordinating the Work and Activities of Others,Developing Objectives and Strategies,Developing and Building Teams,Documenting/Recording Information,...,Repairing and Maintaining Electronic Equipment,Repairing and Maintaining Mechanical Equipment,Resolving Conflicts and Negotiating with Others,Scheduling Work and Activities,Selling or Influencing Others,Staffing Organizational Units,Thinking Creatively,Training and Teaching Others,Updating and Using Relevant Knowledge,Working with Computers
Title,,,,,,,,,,,,,,,,,,,,,
Accountants and Auditors,1.159499,-0.534333,0.603398,0.596006,1.001259,-1.074465,0.894659,0.501765,1.082599,0.998446,...,-0.874493,-0.940526,0.469208,0.703121,0.397580,1.184422,-0.072168,0.601274,0.429041,1.123678
Actors,-1.588343,-0.750348,-1.097293,0.127050,0.318628,-1.122761,-1.265896,-1.577593,-1.001834,-1.539419,...,-0.910008,-0.899312,-1.236907,-1.375902,-0.759643,-1.022355,1.092497,-1.147888,-2.298659,-1.588295
Actuaries,2.483850,-1.000043,0.676687,0.479067,1.084054,-1.116227,-0.135361,0.816356,0.309618,-0.307873,...,-0.954980,-0.984367,-0.237229,-0.306986,0.108992,0.809427,0.370019,-0.276489,0.888953,1.410877
Acupuncturists,-0.092295,2.280607,-0.058512,0.046606,-1.857596,-1.039515,-1.441935,0.175843,-1.254243,1.100708,...,-0.696814,-0.779431,-0.540615,0.100376,0.489219,-0.115985,0.278472,-0.661021,0.791104,-0.726251
Acute Care Nurses,0.382139,2.319541,0.876570,-0.185377,0.769209,-0.054827,0.628252,-0.154983,1.098668,1.361223,...,-0.009392,-0.516815,0.928429,0.108500,-0.657484,1.873222,0.145968,1.138806,0.856189,0.356596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wind Turbine Service Technicians,0.078593,0.307604,0.297139,-1.024590,0.472464,2.450616,0.414303,-0.288439,0.595413,0.477118,...,4.969019,3.871428,-0.312258,-0.279164,-0.793356,-0.566852,-0.323446,0.552305,0.096071,0.317679
"Woodworking Machine Setters, Operators, and Tenders, Except Sawing",-1.237425,-0.962065,-1.585154,-1.768925,-1.780572,1.392107,-1.074887,-1.546805,-1.239178,-1.434954,...,-0.273551,0.145046,-1.675858,-1.899660,-1.203514,-1.104906,-1.192501,-1.455838,-1.774789,-1.529092
Word Processors and Typists,-0.709680,-0.031532,-1.272101,-0.101932,-0.071820,-0.623257,-1.463353,-1.285764,-1.326461,-0.029748,...,-0.717898,-0.788312,-0.442789,-0.977712,-1.090161,-0.819715,-0.935947,-1.440117,-1.252062,0.232829
Writers and Authors,-1.380116,-0.851348,-0.503076,1.853610,0.774811,-1.257612,0.410962,1.019064,0.178348,-1.599083,...,-0.980463,-0.996475,-0.571128,-0.064936,3.573838,-0.756755,0.570035,-0.758322,0.275344,-0.667175
Zoologists and Wildlife Biologists,0.717833,-0.356282,0.120932,1.520780,0.865203,-0.257909,0.902038,1.676572,1.207487,0.006152,...,-0.537201,-0.051125,1.015541,1.454472,0.101753,0.742628,0.727752,-0.056173,0.319599,0.626857

In [109]:
wa_c.columns

Index(['O*NET-SOC Code', 'Title', 'Element Name', 'importance', 'level',
       'combined_score', 'activity_score'],
      dtype='object', name='Scale ID')

In [110]:
wa_filtered=wa_c[['O*NET-SOC Code', 'Title', 'Element Name','activity_score']]

In [111]:
wa_filtered.to_csv("workactivity_job.csv")

In [112]:
wa_final.to_csv("workactivity_job_matrix.csv")

In [113]:
tech_job=pd.read_csv("Technology Skills.csv")

In [114]:
tech_job

,O*NET-SOC Code,Title,Example,Commodity Code,Commodity Title,Hot Technology,In Demand
0,11-1011.00,Chief Executives,Adobe Acrobat,43232202,Document management software,Y,N
1,11-1011.00,Chief Executives,AdSense Tracker,43232306,Data base user interface and query software,N,N
2,11-1011.00,Chief Executives,Atlassian JIRA,43232201,Content workflow software,Y,N
3,11-1011.00,Chief Executives,Blackbaud The Raiser's Edge,43232303,Customer relationship management CRM software,N,N
4,11-1011.00,Chief Executives,ComputerEase construction accounting software,43231601,Accounting software,N,N
...,...,...,...,...,...,...,...
32768,53-7121.00,"Tank Car, Truck, and Ship Loaders",Linux,43233004,Operating system software,Y,N
32769,53-7121.00,"Tank Car, Truck, and Ship Loaders",Microsoft Excel,43232110,Spreadsheet software,Y,N
32770,53-7121.00,"Tank Car, Truck, and Ship Loaders",Microsoft Office software,43231513,Office suite software,Y,N
32771,53-7121.00,"Tank Car, Truck, and Ship Loaders",SAP software,43231602,Enterprise resource planning ERP software,Y,N
32772,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse management system WMS,43231506,Materials requirements planning logistics and ...,N,N

In [115]:
%pip install pandas pymongo

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.3.3)
Collecting pymongo
  Downloading pymongo-4.16.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (10.0 kB)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pymongo) (2.8.0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymongo-4.16.0-cp312-cp312-macosx_11_0_arm64.whl (917 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 917.4/917.4 kB 4.1 MB/s  0:00:00 eta 0:00:01
Installing collected packages: pymongo
Successfully installed pymongo-4.16.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [117]:
from pymongo import MongoClient
from urllib.parse import quote_plus

username = "career_ai"
password = quote_plus("W@ter15life")

uri = f"mongodb+srv://{username}:{password}@cluster0.gacvoea.mongodb.net/?appName=Cluster0"

client = MongoClient(uri)

db = client["career_recommender"]
collection = db["occupations"]

print("Connected to MongoDB!")

Connected to MongoDB!

In [118]:
job_abilities

Scale ID,O*NET-SOC Code,Title,Element Name,ability_score
0,11-1011.00,Chief Executives,Deductive Reasoning,1.700598
4,11-1011.00,Chief Executives,Mathematical Reasoning,1.240398
5,11-1011.00,Chief Executives,Memorization,1.513427
6,11-1011.00,Chief Executives,Perceptual Speed,0.435258
7,11-1011.00,Chief Executives,Problem Sensitivity,1.695923
...,...,...,...,...
12509,53-7121.00,"Tank Car, Truck, and Ship Loaders",Problem Sensitivity,-0.606360
12510,53-7121.00,"Tank Car, Truck, and Ship Loaders",Selective Attention,0.125927
12512,53-7121.00,"Tank Car, Truck, and Ship Loaders",Speed of Closure,-0.585228
12513,53-7121.00,"Tank Car, Truck, and Ship Loaders",Time Sharing,1.032426
12515,53-7121.00,"Tank Car, Truck, and Ship Loaders",Written Comprehension,-0.938492

In [119]:
wa_filtered

Scale ID,O*NET-SOC Code,Title,Element Name,activity_score
0,11-1011.00,Chief Executives,Analyzing Data or Information,1.113642
1,11-1011.00,Chief Executives,Assisting and Caring for Others,0.045781
2,11-1011.00,Chief Executives,Coaching and Developing Others,3.276915
3,11-1011.00,Chief Executives,Communicating with People Outside the Organiza...,1.999985
4,11-1011.00,Chief Executives,"Communicating with Supervisors, Peers, or Subo...",2.102813
...,...,...,...,...
36649,53-7121.00,"Tank Car, Truck, and Ship Loaders",Staffing Organizational Units,-0.479690
36650,53-7121.00,"Tank Car, Truck, and Ship Loaders",Thinking Creatively,-0.152066
36651,53-7121.00,"Tank Car, Truck, and Ship Loaders",Training and Teaching Others,0.144464
36652,53-7121.00,"Tank Car, Truck, and Ship Loaders",Updating and Using Relevant Knowledge,-0.078899
36653,53-7121.00,"Tank Car, Truck, and Ship Loaders",Working with Computers,-0.817497

In [121]:
grouped = job_abilities.groupby(["O*NET-SOC Code", "Title"])

In [122]:
documents = []

for (code, title), group in grouped:

    ability_dict = dict(zip(group["Element Name"], group["ability_score"]))

    doc = {
        "occupation_code": code,
        "title": title,
        "abilities": ability_dict
    }

    documents.append(doc)

In [131]:
collection.insert_many(documents)

print("Occupations inserted:", len(documents))

Occupations inserted: 894

In [132]:
grouped = wa_filtered.groupby(["O*NET-SOC Code", "Title"])

In [133]:
activity_docs = []

for (code, title), group in grouped:

    activity_dict = dict(zip(group["Element Name"], group["activity_score"]))

    activity_docs.append({
        "occupation_code": code,
        "activities": activity_dict
    })

In [134]:
for doc in activity_docs:
    
    collection.update_one(
        {"occupation_code": doc["occupation_code"]},
        {"$set": {"activities": doc["activities"]}}
    )

In [135]:
for job in collection.find().limit(1):
    print(job)

{'_id': ObjectId('69ac3b255a3700a10bb73dd7'), 'occupation_code': '11-1011.00', 'title': 'Chief Executives', 'abilities': {'Deductive Reasoning': 1.7005977701937627, 'Mathematical Reasoning': 1.2403982129924693, 'Memorization': 1.5134265787124048, 'Perceptual Speed': 0.4352578077844902, 'Problem Sensitivity': 1.695923432803498, 'Selective Attention': 0.12592746916040956, 'Speed of Closure': 1.3824317898250176, 'Time Sharing': 0.8450012669957117, 'Written Comprehension': 1.5293766695010196}, 'activities': {'Analyzing Data or Information': 1.1136416286877664, 'Assisting and Caring for Others': 0.04578108970376047, 'Coaching and Developing Others': 3.276915042175017, 'Communicating with People Outside the Organization': 1.999984875540586, 'Communicating with Supervisors, Peers, or Subordinates': 2.102812588654608, 'Controlling Machines and Processes': -0.7665047636809079, 'Coordinating the Work and Activities of Others': 2.494956279412878, 'Developing Objectives and Strategies': 2.994050634809756, 'Developing and Building Teams': 3.4440790851019747, 'Documenting/Recording Information': 0.015629441228562992, 'Drafting, Laying Out, and Specifying Technical Devices, Parts, and Equipment': -0.5709634676504741, 'Establishing and Maintaining Interpersonal Relationships': 2.8502726623653425, 'Estimating the Quantifiable Characteristics of Products, Events, or Information': 0.180091281653794, 'Evaluating Information to Determine Compliance with Standards': 1.63084811889105, 'Getting Information': 0.8701597472725283, 'Guiding, Directing, and Motivating Subordinates': 3.7745189027267765, 'Handling and Moving Objects': -1.013825223549781, 'Identifying Objects, Actions, and Events': 1.1789210923298394, 'Inspecting Equipment, Structures, or Materials': -0.8609495004950263, 'Interpreting the Meaning of Information for Others': 0.43236685994183366, 'Judging the Qualities of Objects, Services, or People': 1.6649765533685599, 'Making Decisions and Solving Problems': 2.0730315239000516, 'Monitoring Processes, Materials, or Surroundings': 1.470004504245844, 'Monitoring and Controlling Resources': 2.8473647970980673, 'Operating Vehicles, Mechanized Devices, or Equipment': -0.159701921041694, 'Organizing, Planning, and Prioritizing Work': 1.7718319813705952, 'Performing Administrative Activities': 2.422361146294861, 'Performing General Physical Activities': -0.9345863011569927, 'Performing for or Working Directly with the Public': 1.0775796351337223, 'Processing Information': 1.138977098979967, 'Providing Consultation and Advice to Others': 2.0173162900612134, 'Repairing and Maintaining Electronic Equipment': -0.8785524860196404, 'Repairing and Maintaining Mechanical Equipment': -0.9421391878696299, 'Resolving Conflicts and Negotiating with Others': 2.905889044526748, 'Scheduling Work and Activities': 1.182984925738521, 'Selling or Influencing Others': 2.664556220592005, 'Staffing Organizational Units': 3.2730051984546233, 'Thinking Creatively': 0.8896133802560565, 'Training and Teaching Others': 1.2032046882449425, 'Updating and Using Relevant Knowledge': 0.7294854540599223, 'Working with Computers': 0.037306313385392594}}

In [136]:
def tech_weight(row):

    hot = row["Hot Technology"]
    demand = row["In Demand"]

    if hot == "Y" and demand == "Y":
        return 2.0
    elif hot == "Y" and demand == "N":
        return 1.5
    elif hot == "N" and demand == "Y":
        return 1.5
    else:
        return 1.0

In [137]:
tech_job["weight"] = tech_job.apply(tech_weight, axis=1)

In [142]:
grouped = tech_job.groupby("O*NET-SOC Code")

tech_docs = []

for code, group in grouped:

    total_weight = group["weight"].sum()

    normalized = {
        tech: w / total_weight
        for tech, w in zip(group["Example"], group["weight"])
    }

    tech_docs.append({
        "occupation_code": code,
        "technologies": normalized
    })

In [145]:
for doc in tech_docs:

    collection.update_one(
        {"occupation_code": doc["occupation_code"]},
        {"$set": {"technologies": doc["technologies"]}}
    )

In [146]:
job = collection.find_one()

print(job)

{'_id': ObjectId('69ac3b255a3700a10bb73dd7'), 'occupation_code': '11-1011.00', 'title': 'Chief Executives', 'abilities': {'Deductive Reasoning': 1.7005977701937627, 'Mathematical Reasoning': 1.2403982129924693, 'Memorization': 1.5134265787124048, 'Perceptual Speed': 0.4352578077844902, 'Problem Sensitivity': 1.695923432803498, 'Selective Attention': 0.12592746916040956, 'Speed of Closure': 1.3824317898250176, 'Time Sharing': 0.8450012669957117, 'Written Comprehension': 1.5293766695010196}, 'activities': {'Analyzing Data or Information': 1.1136416286877664, 'Assisting and Caring for Others': 0.04578108970376047, 'Coaching and Developing Others': 3.276915042175017, 'Communicating with People Outside the Organization': 1.999984875540586, 'Communicating with Supervisors, Peers, or Subordinates': 2.102812588654608, 'Controlling Machines and Processes': -0.7665047636809079, 'Coordinating the Work and Activities of Others': 2.494956279412878, 'Developing Objectives and Strategies': 2.994050634809756, 'Developing and Building Teams': 3.4440790851019747, 'Documenting/Recording Information': 0.015629441228562992, 'Drafting, Laying Out, and Specifying Technical Devices, Parts, and Equipment': -0.5709634676504741, 'Establishing and Maintaining Interpersonal Relationships': 2.8502726623653425, 'Estimating the Quantifiable Characteristics of Products, Events, or Information': 0.180091281653794, 'Evaluating Information to Determine Compliance with Standards': 1.63084811889105, 'Getting Information': 0.8701597472725283, 'Guiding, Directing, and Motivating Subordinates': 3.7745189027267765, 'Handling and Moving Objects': -1.013825223549781, 'Identifying Objects, Actions, and Events': 1.1789210923298394, 'Inspecting Equipment, Structures, or Materials': -0.8609495004950263, 'Interpreting the Meaning of Information for Others': 0.43236685994183366, 'Judging the Qualities of Objects, Services, or People': 1.6649765533685599, 'Making Decisions and Solving Problems': 2.0730315239000516, 'Monitoring Processes, Materials, or Surroundings': 1.470004504245844, 'Monitoring and Controlling Resources': 2.8473647970980673, 'Operating Vehicles, Mechanized Devices, or Equipment': -0.159701921041694, 'Organizing, Planning, and Prioritizing Work': 1.7718319813705952, 'Performing Administrative Activities': 2.422361146294861, 'Performing General Physical Activities': -0.9345863011569927, 'Performing for or Working Directly with the Public': 1.0775796351337223, 'Processing Information': 1.138977098979967, 'Providing Consultation and Advice to Others': 2.0173162900612134, 'Repairing and Maintaining Electronic Equipment': -0.8785524860196404, 'Repairing and Maintaining Mechanical Equipment': -0.9421391878696299, 'Resolving Conflicts and Negotiating with Others': 2.905889044526748, 'Scheduling Work and Activities': 1.182984925738521, 'Selling or Influencing Others': 2.664556220592005, 'Staffing Organizational Units': 3.2730051984546233, 'Thinking Creatively': 0.8896133802560565, 'Training and Teaching Others': 1.2032046882449425, 'Updating and Using Relevant Knowledge': 0.7294854540599223, 'Working with Computers': 0.037306313385392594}, 'technologies': {'Adobe Acrobat': 0.025423728813559324, 'AdSense Tracker': 0.01694915254237288, 'Atlassian JIRA': 0.025423728813559324, "Blackbaud The Raiser's Edge": 0.01694915254237288, 'ComputerEase construction accounting software': 0.01694915254237288, 'Database reporting software': 0.01694915254237288, 'Databox': 0.01694915254237288, 'Email software': 0.01694915254237288, 'Enterprise resource planning ERP software': 0.01694915254237288, 'Exact Software Macola ES Labor Performance': 0.01694915254237288, 'Extensible markup language XML': 0.025423728813559324, 'Fund accounting software': 0.01694915254237288, 'Graphic presentation software': 0.01694915254237288, 'Halogen e360': 0.01694915254237288, 'Halogen ePraisal': 0.01694915254237288, 'HCSS HeavyBid': 0.01694915254237288, 'HCSS HeavyJob': 0.01694915254237288, 'Human resource information system (HRIS)': 0.01694915254237288, 'Infor SSA Human Capital Management': 0.01694915254237288, 'Intuit QuickBooks': 0.025423728813559324, 'Listserv software': 0.01694915254237288, 'Lyris HQ Web-Analytics Solution': 0.01694915254237288, 'Mentimeter': 0.01694915254237288, 'Microsoft Access': 0.025423728813559324, 'Microsoft Dynamics': 0.01694915254237288, 'Microsoft Dynamics AX': 0.01694915254237288, 'Microsoft Dynamics GP': 0.01694915254237288, 'Microsoft Excel': 0.03389830508474576, 'Microsoft FRx': 0.01694915254237288, 'Microsoft Office software': 0.03389830508474576, 'Microsoft Outlook': 0.03389830508474576, 'Microsoft PowerPoint': 0.03389830508474576, 'Microsoft Project': 0.025423728813559324, 'Microsoft Publisher': 0.01694915254237288, 'Microsoft SharePoint': 0.025423728813559324, 'Microsoft Word': 0.025423728813559324, 'Nedstat Sitestat': 0.01694915254237288, 'Norchard Solutions Succession Wizard': 0.01694915254237288, 'Online advertising reporting software': 0.01694915254237288, 'Oracle E-Business Suite': 0.01694915254237288, 'Oracle PeopleSoft': 0.025423728813559324, 'Oracle Siebel Server Sync': 0.01694915254237288, 'PHP': 0.025423728813559324, 'Relational database management software': 0.01694915254237288, 'Sage 50 Accounting': 0.01694915254237288, 'SAP software': 0.025423728813559324, 'SmugMug Flickr': 0.01694915254237288, 'Structured query language SQL': 0.025423728813559324, 'Web browser software': 0.01694915254237288}}

## possible functions:
1. job predictions (knn, hybrid, cosine)
2. clustered jobs: Cluster 1 — Analytical careers (riasec?)
• Data Scientist
• ML Engineer
• Statistician

Cluster 2 — Social careers
• Teacher
• Counselor
• HR Manager

3. Learning-to-Rank Model (Career Ranking Engine)
What it does

Instead of manually weighting signals:

career_score =
0.4 ability
+ 0.3 activity
+ 0.3 skill

you train a model to learn the best ranking automatically.


4.  Job Embedding Model (Representation Learning)



5. Graph-Based Career Network

In [147]:
import numpy as np

def build_job_vector(job, ability_cols, activity_cols, tech_cols):

    ability_vec = [job["abilities"].get(a, 0) for a in ability_cols]

    activity_vec = [job["activities"].get(a, 0) for a in activity_cols]

    tech_vec = [job["technologies"].get(t, 0) for t in tech_cols]

    return np.array(ability_vec + activity_vec + tech_vec)

In [149]:
import pandas as pd

grouped = tech_job.groupby("O*NET-SOC Code")

tech_docs = []
tech_rows = []

for code, group in grouped:

    total_weight = group["weight"].sum()

    normalized = {
        tech: w / total_weight
        for tech, w in zip(group["Example"], group["weight"])
    }

    # Mongo document
    tech_docs.append({
        "occupation_code": code,
        "technologies": normalized
    })

    # DataFrame row
    row = {"occupation_code": code}
    row.update(normalized)

    tech_rows.append(row)

# Create dataframe
tech_df = pd.DataFrame(tech_rows).fillna(0)

In [150]:
tech_df

,occupation_code,Adobe Acrobat,AdSense Tracker,Atlassian JIRA,Blackbaud The Raiser's Edge,ComputerEase construction accounting software,Database reporting software,Databox,Email software,Enterprise resource planning ERP software,...,Thoughtful Systems Scheduling Manager for Auto Detailing,Work time tracking software,Ordering software,Voice picking software,Moxa software,AMCS Platform,Dossier software,Mileage logging software,Routeware software,CompuWeigh GMS
0,11-1011.00,0.025424,0.016949,0.025424,0.016949,0.016949,0.016949,0.016949,0.016949,0.016949,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
1,11-1011.03,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
2,11-1021.00,0.008721,0.000000,0.008721,0.005814,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
3,11-1031.00,0.040000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
4,11-2011.00,0.016760,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011173,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,53-7071.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
919,53-7072.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
920,53-7073.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.095238,0.0,0.0,0.0,0.0,0.000000
921,53-7081.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.1,0.1,0.1,0.1,0.000000
922,53-7121.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.111111

In [152]:
ja_pivot

Element Name,Deductive Reasoning,Mathematical Reasoning,Memorization,Perceptual Speed,Problem Sensitivity,Selective Attention,Speed of Closure,Time Sharing,Written Comprehension
Title,,,,,,,,,
Accountants and Auditors,1.018582,1.357991,-0.124991,0.109817,0.613903,-0.981324,0.901529,-0.749085,0.635983
Actors,-1.065427,-1.699426,4.736982,-1.838489,-0.905604,0.125927,-0.689027,0.641958,0.024271
Actuaries,1.687944,3.872671,0.163898,-0.033377,0.756294,1.117597,0.256172,-0.778912,1.163611
Acupuncturists,0.557847,-0.734560,-0.946074,-0.343631,0.508732,-0.093765,-0.810877,-0.670449,0.322770
Acute Care Nurses,1.043736,0.384683,1.342935,0.435258,2.020264,0.601929,1.551398,1.227660,1.082680
...,...,...,...,...,...,...,...,...,...
Wind Turbine Service Technicians,0.302553,-0.548824,0.987744,0.753929,0.356026,0.354408,0.571223,1.219851,-0.610038
"Woodworking Machine Setters, Operators, and Tenders, Except Sawing",-1.065427,-0.792452,-1.064471,0.591469,-1.005139,1.306410,0.260956,-0.456234,-1.086816
Word Processors and Typists,-1.065427,-0.620127,-1.192734,0.435258,-1.387966,-1.403135,-0.689027,-1.359191,0.023220
Writers and Authors,-0.583182,-1.532986,-0.712042,-1.951308,-0.797774,-1.390563,0.256172,-0.941607,0.850397
Zoologists and Wildlife Biologists,0.797148,0.471521,-0.566217,0.109817,0.374636,0.859763,-0.049311,1.227660,1.373821

In [153]:
wa_final

Element Name,Analyzing Data or Information,Assisting and Caring for Others,Coaching and Developing Others,Communicating with People Outside the Organization,"Communicating with Supervisors, Peers, or Subordinates",Controlling Machines and Processes,Coordinating the Work and Activities of Others,Developing Objectives and Strategies,Developing and Building Teams,Documenting/Recording Information,...,Repairing and Maintaining Electronic Equipment,Repairing and Maintaining Mechanical Equipment,Resolving Conflicts and Negotiating with Others,Scheduling Work and Activities,Selling or Influencing Others,Staffing Organizational Units,Thinking Creatively,Training and Teaching Others,Updating and Using Relevant Knowledge,Working with Computers
Title,,,,,,,,,,,,,,,,,,,,,
Accountants and Auditors,1.159499,-0.534333,0.603398,0.596006,1.001259,-1.074465,0.894659,0.501765,1.082599,0.998446,...,-0.874493,-0.940526,0.469208,0.703121,0.397580,1.184422,-0.072168,0.601274,0.429041,1.123678
Actors,-1.588343,-0.750348,-1.097293,0.127050,0.318628,-1.122761,-1.265896,-1.577593,-1.001834,-1.539419,...,-0.910008,-0.899312,-1.236907,-1.375902,-0.759643,-1.022355,1.092497,-1.147888,-2.298659,-1.588295
Actuaries,2.483850,-1.000043,0.676687,0.479067,1.084054,-1.116227,-0.135361,0.816356,0.309618,-0.307873,...,-0.954980,-0.984367,-0.237229,-0.306986,0.108992,0.809427,0.370019,-0.276489,0.888953,1.410877
Acupuncturists,-0.092295,2.280607,-0.058512,0.046606,-1.857596,-1.039515,-1.441935,0.175843,-1.254243,1.100708,...,-0.696814,-0.779431,-0.540615,0.100376,0.489219,-0.115985,0.278472,-0.661021,0.791104,-0.726251
Acute Care Nurses,0.382139,2.319541,0.876570,-0.185377,0.769209,-0.054827,0.628252,-0.154983,1.098668,1.361223,...,-0.009392,-0.516815,0.928429,0.108500,-0.657484,1.873222,0.145968,1.138806,0.856189,0.356596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wind Turbine Service Technicians,0.078593,0.307604,0.297139,-1.024590,0.472464,2.450616,0.414303,-0.288439,0.595413,0.477118,...,4.969019,3.871428,-0.312258,-0.279164,-0.793356,-0.566852,-0.323446,0.552305,0.096071,0.317679
"Woodworking Machine Setters, Operators, and Tenders, Except Sawing",-1.237425,-0.962065,-1.585154,-1.768925,-1.780572,1.392107,-1.074887,-1.546805,-1.239178,-1.434954,...,-0.273551,0.145046,-1.675858,-1.899660,-1.203514,-1.104906,-1.192501,-1.455838,-1.774789,-1.529092
Word Processors and Typists,-0.709680,-0.031532,-1.272101,-0.101932,-0.071820,-0.623257,-1.463353,-1.285764,-1.326461,-0.029748,...,-0.717898,-0.788312,-0.442789,-0.977712,-1.090161,-0.819715,-0.935947,-1.440117,-1.252062,0.232829
Writers and Authors,-1.380116,-0.851348,-0.503076,1.853610,0.774811,-1.257612,0.410962,1.019064,0.178348,-1.599083,...,-0.980463,-0.996475,-0.571128,-0.064936,3.573838,-0.756755,0.570035,-0.758322,0.275344,-0.667175
Zoologists and Wildlife Biologists,0.717833,-0.356282,0.120932,1.520780,0.865203,-0.257909,0.902038,1.676572,1.207487,0.006152,...,-0.537201,-0.051125,1.015541,1.454472,0.101753,0.742628,0.727752,-0.056173,0.319599,0.626857

In [154]:
tech_matrix = tech_job.pivot_table(
    index="O*NET-SOC Code",
    columns="Example",
    values="weight",
    fill_value=0
)

In [155]:
tech_matrix

Example,!Trak-it Solutions !Trak-it HR,100 Plus Hatch Pattern Library,1003 Uniform Residential Loan Application,1099 ProsSoftware,1CadCam Unigraphics,1ST Pricing Window & Door Toolkit,20-20 Technologies 20-20 Design,24SevenOffice Project,2AB iLock Security Services,360 Analytics eQUEST,...,spaCy,techniques.org knowledgeWorks LMS,vtiger CRM,web2project,webpack,xQuery,xv,yieldWerx,z-Tree,zkipster
O*NET-SOC Code,,,,,,,,,,,,,,,,,,,,,
11-1011.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11-1011.03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11-1021.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11-1031.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11-2011.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53-7071.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53-7072.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53-7073.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53-7081.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53-7121.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [159]:
tech_matrix = tech_df.drop(columns=["occupation_code"])

In [161]:
occupation_codes = tech_df["occupation_code"]

In [162]:
import numpy as np

tech_vectors = tech_matrix.values

In [163]:
tech_vectors.shape

(923, 8785)

In [164]:
from scipy.sparse import csr_matrix

tech_sparse = csr_matrix(tech_vectors)

In [173]:
ability_matrix=ja_pivot

In [174]:
activity_matrix=wa_final

In [171]:
job_abilities.columns

Index(['O*NET-SOC Code', 'Title', 'Element Name', 'ability_score'], dtype='object', name='Scale ID')

In [172]:
title_map = job_abilities.set_index("O*NET-SOC Code")["Title"]

In [175]:
ability_matrix["occupation_code"] = ability_matrix.index.map(
    {v: k for k, v in title_map.items()}
)

ability_matrix = ability_matrix.set_index("occupation_code")

In [176]:
activity_matrix["occupation_code"] = activity_matrix.index.map(
    {v: k for k, v in title_map.items()}
)

activity_matrix = activity_matrix.set_index("occupation_code")

In [192]:
job_order = tech_matrix.index

In [193]:
tech_matrix.index

RangeIndex(start=0, stop=923, step=1)

In [194]:
ability_matrix["occupation_code"] = ability_matrix.index.map(title_map)
ability_matrix = ability_matrix.set_index("occupation_code")

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [195]:
ability_matrix = ability_matrix.loc[job_order]
activity_matrix = activity_matrix.loc[job_order]

KeyError: 'None of [RangeIndex(start=0, stop=923, step=1)] are in the [index]'

In [198]:
ability_matrix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 894 entries, 13-2011.00 to 19-1023.00
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Deductive Reasoning     894 non-null    float64
 1   Mathematical Reasoning  894 non-null    float64
 2   Memorization            894 non-null    float64
 3   Perceptual Speed        894 non-null    float64
 4   Problem Sensitivity     894 non-null    float64
 5   Selective Attention     894 non-null    float64
 6   Speed of Closure        894 non-null    float64
 7   Time Sharing            894 non-null    float64
 8   Written Comprehension   894 non-null    float64
dtypes: float64(9)
memory usage: 102.1+ KB

In [199]:
activity_matrix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 894 entries, 13-2011.00 to 19-1023.00
Data columns (total 41 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   Analyzing Data or Information                                                    894 non-null    float64
 1   Assisting and Caring for Others                                                  894 non-null    float64
 2   Coaching and Developing Others                                                   894 non-null    float64
 3   Communicating with People Outside the Organization                               894 non-null    float64
 4   Communicating with Supervisors, Peers, or Subordinates                           894 non-null    float64
 5   Controlling Machines and Processes                                               894 non-null    float64
 6   Coordinating the Work and Activities of Others                                   894 non-null    float64
 7   Developing Objectives and Strategies                                             894 non-null    float64
 8   Developing and Building Teams                                                    894 non-null    float64
 9   Documenting/Recording Information                                                894 non-null    float64
 10  Drafting, Laying Out, and Specifying Technical Devices, Parts, and Equipment     894 non-null    float64
 11  Establishing and Maintaining Interpersonal Relationships                         894 non-null    float64
 12  Estimating the Quantifiable Characteristics of Products, Events, or Information  894 non-null    float64
 13  Evaluating Information to Determine Compliance with Standards                    894 non-null    float64
 14  Getting Information                                                              894 non-null    float64
 15  Guiding, Directing, and Motivating Subordinates                                  894 non-null    float64
 16  Handling and Moving Objects                                                      894 non-null    float64
 17  Identifying Objects, Actions, and Events                                         894 non-null    float64
 18  Inspecting Equipment, Structures, or Materials                                   894 non-null    float64
 19  Interpreting the Meaning of Information for Others                               894 non-null    float64
 20  Judging the Qualities of Objects, Services, or People                            894 non-null    float64
 21  Making Decisions and Solving Problems                                            894 non-null    float64
 22  Monitoring Processes, Materials, or Surroundings                                 894 non-null    float64
 23  Monitoring and Controlling Resources                                             894 non-null    float64
 24  Operating Vehicles, Mechanized Devices, or Equipment                             894 non-null    float64
 25  Organizing, Planning, and Prioritizing Work                                      894 non-null    float64
 26  Performing Administrative Activities                                             894 non-null    float64
 27  Performing General Physical Activities                                           894 non-null    float64
 28  Performing for or Working Directly with the Public                               894 non-null    float64
 29  Processing Information                                                           894 non-null    float64
 30  Providing Consultation and Advice to Others                                      894 non-null    float64
 31  Repairing and Maintaining Electronic Equipment                                   894 non-null    float64
 32  Repairing and Maintaining Mechanical Equipment                                   894 non-null    float64
 33  Resolving Conflicts and Negotiating with Others                                  894 non-null    float64
 34  Scheduling Work and Activities                                                   894 non-null    float64
 35  Selling or Influencing Others                                                    894 non-null    float64
 36  Staffing Organizational Units                                                    894 non-null    float64
 37  Thinking Creatively                                                              894 non-null    float64
 38  Training and Teaching Others                                                     894 non-null    float64
 39  Updating and Using Relevant Knowledge                                            894 non-null    float64
 40  Working with Computers                                                           894 non-null    float64
dtypes: float64(41)
memory usage: 293.3+ KB

In [200]:
tech_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 923 entries, 11-1011.00 to 53-7121.00
Columns: 8785 entries, Adobe Acrobat to CompuWeigh GMS
dtypes: float64(8785)
memory usage: 61.9+ MB

In [188]:
tech_df

,occupation_code,Adobe Acrobat,AdSense Tracker,Atlassian JIRA,Blackbaud The Raiser's Edge,ComputerEase construction accounting software,Database reporting software,Databox,Email software,Enterprise resource planning ERP software,...,Thoughtful Systems Scheduling Manager for Auto Detailing,Work time tracking software,Ordering software,Voice picking software,Moxa software,AMCS Platform,Dossier software,Mileage logging software,Routeware software,CompuWeigh GMS
0,11-1011.00,0.025424,0.016949,0.025424,0.016949,0.016949,0.016949,0.016949,0.016949,0.016949,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
1,11-1011.03,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
2,11-1021.00,0.008721,0.000000,0.008721,0.005814,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
3,11-1031.00,0.040000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
4,11-2011.00,0.016760,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011173,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,53-7071.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
919,53-7072.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
920,53-7073.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.095238,0.0,0.0,0.0,0.0,0.000000
921,53-7081.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.1,0.1,0.1,0.1,0.000000
922,53-7121.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.111111

In [190]:
tech_df = tech_df.set_index("occupation_code")

In [191]:
tech_df

,Adobe Acrobat,AdSense Tracker,Atlassian JIRA,Blackbaud The Raiser's Edge,ComputerEase construction accounting software,Database reporting software,Databox,Email software,Enterprise resource planning ERP software,Exact Software Macola ES Labor Performance,...,Thoughtful Systems Scheduling Manager for Auto Detailing,Work time tracking software,Ordering software,Voice picking software,Moxa software,AMCS Platform,Dossier software,Mileage logging software,Routeware software,CompuWeigh GMS
occupation_code,,,,,,,,,,,,,,,,,,,,,
11-1011.00,0.025424,0.016949,0.025424,0.016949,0.016949,0.016949,0.016949,0.016949,0.016949,0.016949,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
11-1011.03,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
11-1021.00,0.008721,0.000000,0.008721,0.005814,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
11-1031.00,0.040000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
11-2011.00,0.016760,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011173,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53-7071.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
53-7072.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
53-7073.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.095238,0.0,0.0,0.0,0.0,0.000000
53-7081.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.1,0.1,0.1,0.1,0.000000
53-7121.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.111111

In [202]:
common_jobs = (
    tech_df.index
    .intersection(activity_matrix.index)
    .intersection(ability_matrix.index)
)

In [203]:
common_jobs

Index(['11-1011.00', '11-1011.03', '11-1021.00', '11-2011.00', '11-2021.00',
       '11-2022.00', '11-2033.00', '11-3012.00', '11-3013.00', '11-3013.01',
       ...
       '53-7062.00', '53-7062.04', '53-7063.00', '53-7064.00', '53-7065.00',
       '53-7071.00', '53-7072.00', '53-7073.00', '53-7081.00', '53-7121.00'],
      dtype='object', name='occupation_code', length=894)

In [204]:
tech_matrix = tech_df.loc[common_jobs]
activity_matrix = activity_matrix.loc[common_jobs]
ability_matrix = ability_matrix.loc[common_jobs]

In [205]:
print(tech_matrix.shape)
print(activity_matrix.shape)
print(ability_matrix.shape)

(894, 8785)
(894, 41)
(894, 9)

In [206]:
ability_vectors = ability_matrix.values
activity_vectors = activity_matrix.values
tech_vectors = tech_matrix.values

In [207]:
from sklearn.metrics.pairwise import cosine_similarity

In [292]:
user_ability = np.array([
0.9,  # Deductive Reasoning
0.95, # Mathematical Reasoning
0.6,  # Memorization
0.7,  # Perceptual Speed
0.9,  # Problem Sensitivity
0.7,  # Selective Attention
0.8,  # Speed of Closure
0.6,  # Time Sharing
0.8   # Written Comprehension
])

In [293]:
user_activity = np.zeros(len(activity_matrix.columns))

In [306]:
user_activity = np.array([
0.95, # Analyzing Data
0.1,
0.3,
0.4,
0.5,
0.1,
0.2,
0.3,
0.2,
0.4,
0.1,
0.2,
0.3,
0.5,
0.4,
0.2,
0.1,
0.1,
0.2,
0.4,
0.7,
0.4,
0.1,
0.3,
0.4,
0.5,
0.9  # Working with Computers
])

In [307]:
user_skill = np.zeros(len(tech_matrix.columns))

user_skills = [
"Python",
"SQL",
"Microsoft Excel",
"TensorFlow",
"PyTorch",
"Scikit-learn",
"Jupyter Notebook"
]

for skill in user_skills:
    if skill in tech_matrix.columns:
        idx = tech_matrix.columns.get_loc(skill)
        user_skill[idx] = 1

In [308]:
from sklearn.metrics.pairwise import cosine_similarity

In [309]:
ability_sim = cosine_similarity(user_ability.reshape(1,-1), ability_matrix.values)

activity_sim = cosine_similarity(user_activity.reshape(1,-1), activity_matrix.values)

skill_sim = cosine_similarity(user_skill.reshape(1,-1), tech_matrix.values)

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 27 while Y.shape[1] == 41

In [298]:
final_score = (
    0.4 * ability_sim +
    0.3 * activity_sim +
    0.3 * skill_sim
)

In [299]:
import numpy as np

top_idx = np.argsort(final_score[0])[::-1][:10]

recommended_jobs = ability_matrix.index[top_idx]

In [300]:
print(recommended_jobs)

Index(['17-2141.01', '19-1042.00', '19-2021.00', '19-1029.01', '15-2099.01',
       '19-1041.00', '17-3026.01', '19-1029.02', '11-9121.02', '17-2161.00'],
      dtype='object', name='occupation_code')

In [301]:
recommended_titles = title_map.loc[recommended_jobs]

In [302]:
recommended_titles

occupation_code
17-2141.01    Fuel Cell Engineers
17-2141.01    Fuel Cell Engineers
17-2141.01    Fuel Cell Engineers
17-2141.01    Fuel Cell Engineers
17-2141.01    Fuel Cell Engineers
                     ...
17-2161.00      Nuclear Engineers
17-2161.00      Nuclear Engineers
17-2161.00      Nuclear Engineers
17-2161.00      Nuclear Engineers
17-2161.00      Nuclear Engineers
Name: Title, Length: 90, dtype: object

In [303]:
code_to_title = (
    job_abilities[["O*NET-SOC Code", "Title"]]
    .drop_duplicates(subset="O*NET-SOC Code")
    .set_index("O*NET-SOC Code")["Title"]
)

In [304]:
recommended_titles = code_to_title.loc[recommended_jobs]

In [305]:
recommended_titles

occupation_code
17-2141.01                                  Fuel Cell Engineers
19-1042.00           Medical Scientists, Except Epidemiologists
19-2021.00                     Atmospheric and Space Scientists
19-1029.01                            Bioinformatics Scientists
15-2099.01                           Bioinformatics Technicians
19-1041.00                                      Epidemiologists
17-3026.01    Nanotechnology Engineering Technologists and T...
19-1029.02                    Molecular and Cellular Biologists
11-9121.02                           Water Resource Specialists
17-2161.00                                    Nuclear Engineers
Name: Title, dtype: object